// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    /// <summary>
    /// A list of details.
    /// </summary>
    [JsonConverter(typeof(DetailsJsonConverter))]
    public class Details
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public IList<Detail> Value { get; set; }
    }

    public class DetailsJsonConverter : JsonConverter<Details>
    {
        public override Details Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new Details { Value = JsonSerializer.Deserialize<IList<Detail>>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, Details value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<IList<Detail>>(writer, value.Value, options);
        }
    }
}
