// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Senzing
{
    /// <summary>
    /// A list of errors.  Usually a stack of errors.
    /// </summary>
    [JsonConverter(typeof(ErrorsJsonConverter))]
    public class Errors
    {
        /// <summary>
        /// The underlying data being wrapped.
        /// </summary>
        public IList<Error> Value { get; set; }
    }

    public class ErrorsJsonConverter : JsonConverter<Errors>
    {
        public override Errors Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            return new Errors { Value = JsonSerializer.Deserialize<IList<Error>>(ref reader, options) };
        }

        public override void Write(Utf8JsonWriter writer, Errors value, JsonSerializerOptions options)
        {
            JsonSerializer.Serialize<IList<Error>>(writer, value.Value, options);
        }
    }
}
