// Code generated by jtd-codegen for C# + System.Text.Json v0.2.1

using System.Text.Json.Serialization;

namespace Senzing
{
    public class SenzingMessage
    {
        [JsonPropertyName("details")]
        public Details Details { get; set; }

        [JsonPropertyName("duration")]
        public int Duration { get; set; }

        [JsonPropertyName("errors")]
        public Errors Errors { get; set; }

        /// <summary>
        /// The unique identification of the message.
        /// </summary>
        [JsonPropertyName("id")]
        public string Id { get; set; }

        /// <summary>
        /// Log level.  Possible values: TRACE, DEBUG, INFO, WARN, ERROR, FATAL,
        /// or PANIC.
        /// </summary>
        [JsonPropertyName("level")]
        public string Level { get; set; }

        /// <summary>
        /// Location in the code.
        /// </summary>
        [JsonPropertyName("location")]
        public string Location { get; set; }

        [JsonPropertyName("status")]
        public string Status { get; set; }

        [JsonPropertyName("text")]
        public object Text { get; set; }

        /// <summary>
        /// Time message was generated in RFC3339 format.
        /// </summary>
        [JsonPropertyName("time")]
        public string Time { get; set; }
    }
}
