// Code generated by jtd-codegen for TypeScript v0.2.1

export type Senzingapi = any;

export type Details = any;

export type Duration = number;

export type Errors = any;

export type Id = string;

export type Level = string;

export type Location = string;

export type Status = string;

export type Text = any;

export type Time = string;
