// Code generated by jtd-codegen for TypeScript v0.2.1

export interface SenzingMessage {
  details: Details;
  duration: number;
  errors: Errors;

  /**
   * The unique identification of the message.
   */
  id: string;

  /**
   * Log level.  Possible values: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, or
   * PANIC.
   */
  level: string;

  /**
   * Location in the code.
   */
  location: string;
  status: string;
  text: any;

  /**
   * Time message was generated in RFC3339 format.
   */
  time: string;
}

export interface Detail {
  key: string;
  position: number;
  value: any;
  valueAsString: string;
}

export type Details = Detail[];

export type Error = string;

export type Errors = Error[];
