// Code generated by jtd-codegen for TypeScript v0.2.1

export interface SenzingMessage {
  /**
   * A list of objects sent to the message generator.
   */
  details: Details;

  /**
   * Time duration reported by the message.
   */
  duration: number;

  /**
   * A list of errors.  Usually a stack of errors.
   */
  errors: Errors;

  /**
   * The unique identification of the message.
   */
  id: string;

  /**
   * Log level.  Possible values: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, or
   * PANIC.
   */
  level: string;

  /**
   * Location in the code identifying where the message was generated.
   */
  location: string;

  /**
   * User-defined status of message.
   */
  status: string;

  /**
   * Text representation of the message.
   */
  text: string;

  /**
   * Time message was generated in RFC3339 format.
   */
  time: string;
}

/**
 * A detail published by the message generator.
 */
export interface Detail {
  /**
   * The unique identifier of the detail.
   */
  key: string;

  /**
   * The order in which the detail was given to the message generator.
   */
  position: number;

  /**
   * Datatype of the value.
   */
  type: string;

  /**
   * The value of the detail in string form.
   */
  value: string;

  /**
   * The value of the detail if it differs from string form.
   */
  valueRaw: any;
}

/**
 * A list of details.
 */
export type Details = Detail[];

/**
 * The text representation of the error.
 */
export type Error = string;

/**
 * A list of errors.  Usually a stack of errors.
 */
export type Errors = Error[];
