// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

/**
 * A detail published by the message generator.
 */
@JsonSerialize
public class Detail {
    @JsonProperty("key")
    private String key;

    @JsonProperty("position")
    private Integer position;

    @JsonProperty("type")
    private String type;

    @JsonProperty("value")
    private String value;

    @JsonProperty("valueRaw")
    private Object valueRaw;

    public Detail() {
    }

    /**
     * Getter for key.<p>
     * The unique identifier of the detail.
     */
    public String getKey() {
        return key;
    }

    /**
     * Setter for key.<p>
     * The unique identifier of the detail.
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for position.<p>
     * The order in which the detail was given to the message generator.
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * Setter for position.<p>
     * The order in which the detail was given to the message generator.
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * Getter for type.<p>
     * Datatype of the value.
     */
    public String getType() {
        return type;
    }

    /**
     * Setter for type.<p>
     * Datatype of the value.
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * Getter for value.<p>
     * The value of the detail in string form.
     */
    public String getValue() {
        return value;
    }

    /**
     * Setter for value.<p>
     * The value of the detail in string form.
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * Getter for valueRaw.<p>
     * The value of the detail if it differs from string form.
     */
    public Object getValueRaw() {
        return valueRaw;
    }

    /**
     * Setter for valueRaw.<p>
     * The value of the detail if it differs from string form.
     */
    public void setValueRaw(Object valueRaw) {
        this.valueRaw = valueRaw;
    }
}
