// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class Detail {
    @JsonProperty("key")
    private String key;

    @JsonProperty("position")
    private Integer position;

    @JsonProperty("value")
    private Object value;

    @JsonProperty("valueAsString")
    private String valueAsString;

    public Detail() {
    }

    /**
     * Getter for key.<p>
     */
    public String getKey() {
        return key;
    }

    /**
     * Setter for key.<p>
     */
    public void setKey(String key) {
        this.key = key;
    }

    /**
     * Getter for position.<p>
     */
    public Integer getPosition() {
        return position;
    }

    /**
     * Setter for position.<p>
     */
    public void setPosition(Integer position) {
        this.position = position;
    }

    /**
     * Getter for value.<p>
     */
    public Object getValue() {
        return value;
    }

    /**
     * Setter for value.<p>
     */
    public void setValue(Object value) {
        this.value = value;
    }

    /**
     * Getter for valueAsString.<p>
     */
    public String getValueAsString() {
        return valueAsString;
    }

    /**
     * Setter for valueAsString.<p>
     */
    public void setValueAsString(String valueAsString) {
        this.valueAsString = valueAsString;
    }
}
