// Code generated by jtd-codegen for Java + Jackson v0.2.1

package com.senzing.schema;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;

@JsonSerialize
public class SenzingMessage {
    @JsonProperty("details")
    private Details details;

    @JsonProperty("duration")
    private Integer duration;

    @JsonProperty("errors")
    private Errors errors;

    @JsonProperty("id")
    private String id;

    @JsonProperty("level")
    private String level;

    @JsonProperty("location")
    private String location;

    @JsonProperty("status")
    private String status;

    @JsonProperty("text")
    private Object text;

    @JsonProperty("time")
    private String time;

    public SenzingMessage() {
    }

    /**
     * Getter for details.<p>
     */
    public Details getDetails() {
        return details;
    }

    /**
     * Setter for details.<p>
     */
    public void setDetails(Details details) {
        this.details = details;
    }

    /**
     * Getter for duration.<p>
     */
    public Integer getDuration() {
        return duration;
    }

    /**
     * Setter for duration.<p>
     */
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    /**
     * Getter for errors.<p>
     */
    public Errors getErrors() {
        return errors;
    }

    /**
     * Setter for errors.<p>
     */
    public void setErrors(Errors errors) {
        this.errors = errors;
    }

    /**
     * Getter for id.<p>
     * The unique identification of the message.
     */
    public String getId() {
        return id;
    }

    /**
     * Setter for id.<p>
     * The unique identification of the message.
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * Getter for level.<p>
     * Log level.  Possible values: TRACE, DEBUG, INFO, WARN, ERROR, FATAL,
     * or PANIC.
     */
    public String getLevel() {
        return level;
    }

    /**
     * Setter for level.<p>
     * Log level.  Possible values: TRACE, DEBUG, INFO, WARN, ERROR, FATAL,
     * or PANIC.
     */
    public void setLevel(String level) {
        this.level = level;
    }

    /**
     * Getter for location.<p>
     * Location in the code.
     */
    public String getLocation() {
        return location;
    }

    /**
     * Setter for location.<p>
     * Location in the code.
     */
    public void setLocation(String location) {
        this.location = location;
    }

    /**
     * Getter for status.<p>
     */
    public String getStatus() {
        return status;
    }

    /**
     * Setter for status.<p>
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * Getter for text.<p>
     */
    public Object getText() {
        return text;
    }

    /**
     * Setter for text.<p>
     */
    public void setText(Object text) {
        this.text = text;
    }

    /**
     * Getter for time.<p>
     * Time message was generated in RFC3339 format.
     */
    public String getTime() {
        return time;
    }

    /**
     * Setter for time.<p>
     * Time message was generated in RFC3339 format.
     */
    public void setTime(String time) {
        this.time = time;
    }
}
