// Code generated by jtd-codegen for Go v0.2.1. DO NOT EDIT.

package typedef

type Senzingapi = interface{}

type Details = interface{}

type Duration = int32

type Errors = interface{}

type ID = string

type Level = string

type Location = string

type Status = string

type Text = interface{}

type Time = string
