// Code generated by jtd-codegen for Go v0.2.1. DO NOT EDIT.

package typedef

type SenzingMessage struct {
	Details Details `json:"details"`

	Duration int32 `json:"duration"`

	Errors Errors `json:"errors"`

	// The unique identification of the message.
	ID string `json:"id"`

	// Log level.  Possible values: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, or
	// PANIC.
	Level string `json:"level"`

	// Location in the code.
	Location string `json:"location"`

	Status string `json:"status"`

	Text interface{} `json:"text"`

	// Time message was generated in RFC3339 format.
	Time string `json:"time"`
}

type Detail struct {
	Key string `json:"key"`

	Position int32 `json:"position"`

	Value interface{} `json:"value"`

	ValueAsString string `json:"valueAsString"`
}

type Details = []Detail

type Error = string

type Errors = []Error
