package parser

import (
	"time"
)

// ----------------------------------------------------------------------------
// Types - interface
// ----------------------------------------------------------------------------

// The ParserInterface interface has methods to parse messages generated by
// go-messaging/messenger.
type ParserInterface interface {
	GetDetails() map[string]string
	GetDuration() int64
	GetErrors() []string
	GetId() string
	GetLevel() string
	GetLocation() string
	GetMessage() string
	GetMessageText() string
	GetStatus() string
	GetText() string
	GetTime() time.Time
	IsJson() bool
}

// ----------------------------------------------------------------------------
// Public functions
// ----------------------------------------------------------------------------

/*
The Parse function creates a new instance of ParserInterface.
*/
func Parse(message string) ParserInterface {
	result, _ := ParseWithError(message)
	return result
}

/*
The ParseWithError function creates a new instance of ParserInterface and an error.
*/
func ParseWithError(message string) (ParserInterface, error) {
	var result = &ParserImpl{
		message: message,
	}
	err := result.initialize()
	return result, err
}
