package parser

import (
	"time"
)

// ----------------------------------------------------------------------------
// Types - interface
// ----------------------------------------------------------------------------

// The ParserInterface interface has methods to parse messages generated by
// go-messaging/messenger.
type ParserInterface interface {
	GetDetails() map[string]string
	GetDuration() int64
	GetErrors() []string
	GetId() string
	GetLevel() string
	GetLocation() string
	GetStatus() string
	GetText() string
	GetTime() time.Time
}

// ----------------------------------------------------------------------------
// Public functions
// ----------------------------------------------------------------------------

/*
The Parse function creates a new instance of ParserInterface.
*/
func Parse(message string) (ParserInterface, error) {
	var result = &ParserImpl{
		message: message,
	}
	err := result.initialize()
	return result, err
}
