package parser

import (
	"encoding/json"
	"fmt"
	"strconv"
	"time"

	"github.com/senzing/go-messaging/messenger"
)

// ----------------------------------------------------------------------------
// Types
// ----------------------------------------------------------------------------

// ParserImpl is an type-struct for an implementation of the ParserInterface.
type ParserImpl struct {
	isJson        bool
	message       string
	parseError    error
	parsedMessage messenger.MessageFormat
}

// ----------------------------------------------------------------------------
// Private functions
// ----------------------------------------------------------------------------

// Determine if string is syntactically JSON.
func isJson(unknownString string) bool {
	unknownStringUnescaped, err := strconv.Unquote(unknownString)
	if err != nil {
		unknownStringUnescaped = unknownString
	}
	var jsonString json.RawMessage
	return json.Unmarshal([]byte(unknownStringUnescaped), &jsonString) == nil
}

// ----------------------------------------------------------------------------
// Private methods
// ----------------------------------------------------------------------------

func (parser *ParserImpl) initialize() error {
	var err error = nil
	if isJson(parser.message) {
		err = json.Unmarshal([]byte(parser.message), &parser.parsedMessage)
	} else {
		err = fmt.Errorf("string is not JSON")
	}
	if err == nil {
		parser.isJson = true
	}
	parser.parseError = err
	return err
}

// ----------------------------------------------------------------------------
// Interface methods
// ----------------------------------------------------------------------------

/*
The GetDetails method returns the "details" JSON key value.

Output
  - Map of key/value pairs
*/
func (parser *ParserImpl) GetDetails() map[string]string {
	result := map[string]string{}
	if parser.parsedMessage.Details != nil {
		parsedDetails, ok := parser.parsedMessage.Details.(map[string]interface{})
		if ok {
			for key, value := range parsedDetails {
				result[key] = fmt.Sprint(value)
			}
		}
	}
	return result
}

/*
The GetDuration method returns the "duration" JSON key value.

Output
  - Duration of operation in nanoseconds
*/
func (parser *ParserImpl) GetDuration() int64 {
	return parser.parsedMessage.Duration
}

/*
The GetErrors method returns the "details" JSON key value.

Output
  - A list of error strings
*/
func (parser *ParserImpl) GetErrors() []string {
	result := []string{}
	if parser.parsedMessage.Errors != nil {
		parsedDetails, ok := parser.parsedMessage.Errors.([]interface{})
		if ok {
			for _, value := range parsedDetails {
				result = append(result, fmt.Sprint(value))
			}
		}
	}
	return result
}

/*
The GetId method returns the "details" JSON key value.

Output
  - A unique identifier of the message
*/
func (parser *ParserImpl) GetId() string {
	return parser.parsedMessage.Id
}

/*
The GetLevel method returns the "details" JSON key value.

Output
  - The log level of the message: TRACE, DEBUG, INFO, WARN, ERROR, FATAL, or PANIC
*/
func (parser *ParserImpl) GetLevel() string {
	return parser.parsedMessage.Level
}

/*
The GetLocation method returns the "details" JSON key value.

Output
  - The file and line of the code issuing the message
*/
func (parser *ParserImpl) GetLocation() string {
	return parser.parsedMessage.Location
}

/*
The GetMessage method returns the "details" JSON key value.

Output
  - The original message submitted for parsing
*/
func (parser *ParserImpl) GetMessage() string {
	return parser.message
}

/*
The GetMessageText method returns the "details" JSON key value.

Output
  - Either: 1) The value of the "text" field; 2) The original message submitted for parsing
*/
func (parser *ParserImpl) GetMessageText() string {
	text := parser.GetText()
	if text != "" {
		return text
	}
	return parser.message
}

/*
The GetParseError method returns the "details" JSON key value.

Output
  - An error internal to the Parse processing.  Used for debugging.
*/
func (parser *ParserImpl) GetParseError() error {
	return parser.parseError
}

/*
The GetStatus method returns the "details" JSON key value.

Output
  - A status string generated by the message creator.
*/
func (parser *ParserImpl) GetStatus() string {
	return parser.parsedMessage.Status
}

/*
The GetText method returns the "details" JSON key value.

Output
  - The string value for the "text" JSON key
*/
func (parser *ParserImpl) GetText() string {
	return parser.parsedMessage.Text
}

/*
The GetTime method returns the "details" JSON key value.

Output
  - The time of message creation
*/
func (parser *ParserImpl) GetTime() time.Time {
	result := time.Time{}
	if parser.parsedMessage.Time == "" {
		return result
	}
	result, err := time.Parse(time.RFC3339Nano, parser.parsedMessage.Time)
	if err != nil {
		fmt.Println(err.Error())
		result = time.Time{}
	}
	return result
}

/*
The IsJson method returns the "details" JSON key value.

Output
  - true if the message parsed was in the JSON format.
*/
func (parser *ParserImpl) IsJson() bool {
	return parser.isJson
}
