// Code generated by jtd-codegen for Rust v0.2.1

use serde_json::Value;

pub type Senzingapi = Option<Value>;

pub type Details = Option<Value>;

pub type Duration = i32;

pub type Errors = Option<Value>;

pub type Id = String;

pub type Level = String;

pub type Location = String;

pub type Status = String;

pub type Text = Option<Value>;

pub type Time = String;
